"""
Core domain types for the Ralph pipeline.
"""

from .phase import (
    Phase,
    PhaseTransition,
    PHASE_TRANSITIONS,
    APPROVAL_PHASES,
    ACTIVE_PHASES,
    TERMINAL_PHASES,
    can_transition,
    get_valid_transitions,
    is_approval_phase,
    is_active_phase,
    is_terminal_phase,
    get_next_phase_after_approval,
)

from .message import (
    Message,
    MessageType,
    MessagePriority,
    MessageStatus,
    PhaseCompletePayload,
    ApprovalRequestPayload,
    ApprovalResponsePayload,
    ErrorReportPayload,
    NeedSharedTypePayload,
    create_phase_complete_message,
    create_approval_request,
    create_error_report,
)

from .errors import (
    ErrorCategory,
    ErrorSeverity,
    CompilationError,
    TestFailure,
    TestResults,
    CompilationResults,
    VerificationResults,
    ErrorReport,
    RalphError,
    SpecValidationError,
    InvalidTransitionError,
    ScopeViolationError,
    MaxIterationsError,
    AgentError,
)

from .spec import (
    TypeKind,
    InterfaceMember,
    Interface,
    SharedType,
    ClassDefinition,
    Dependency,
    ChildRef,
    Criterion,
    TechStack,
    Constraints,
    Spec,
    create_spec,
    create_child_spec,
)

__all__ = [
    # Phase
    "Phase",
    "PhaseTransition",
    "PHASE_TRANSITIONS",
    "APPROVAL_PHASES",
    "ACTIVE_PHASES",
    "TERMINAL_PHASES",
    "can_transition",
    "get_valid_transitions",
    "is_approval_phase",
    "is_active_phase",
    "is_terminal_phase",
    "get_next_phase_after_approval",
    # Message
    "Message",
    "MessageType",
    "MessagePriority",
    "MessageStatus",
    "PhaseCompletePayload",
    "ApprovalRequestPayload",
    "ApprovalResponsePayload",
    "ErrorReportPayload",
    "NeedSharedTypePayload",
    "create_phase_complete_message",
    "create_approval_request",
    "create_error_report",
    # Errors
    "ErrorCategory",
    "ErrorSeverity",
    "CompilationError",
    "TestFailure",
    "TestResults",
    "CompilationResults",
    "VerificationResults",
    "ErrorReport",
    "RalphError",
    "SpecValidationError",
    "InvalidTransitionError",
    "ScopeViolationError",
    "MaxIterationsError",
    "AgentError",
    # Spec
    "TypeKind",
    "InterfaceMember",
    "Interface",
    "SharedType",
    "ClassDefinition",
    "Dependency",
    "ChildRef",
    "Criterion",
    "TechStack",
    "Constraints",
    "Spec",
    "create_spec",
    "create_child_spec",
]
